#Steps Specific Configuration
general:
  changeManagement:
    endpoint: 'https://hclsdsm72a.hcldigilabs.com:8002/sap/opu/odata/sap/AI_CRM_GW_CM_CI_SRV'
    credentialsId: 'CM'
    type: 'SOLMAN'
steps:
  mtaBuild:
    buildTarget: 'NEO'
  transportRequestCreate:
    developmentSystemId: 'SM1~ABAP/001'
  transportRequestUploadFile:
    applicationId: 'HCP'
