#Steps Specific Configuration
general:
  changeManagement:
     type:'SOLMAN'
     credentialsId:'CM'
     endpoint: 'https://hclsdsm72a.hcldigilabs.com:8002/sap/opu/odata/sap/AI_CRM_GW_CM_CI_SRV'
    git:
      from: 'HEAD~1'
      to: 'HEAD'
      format: '%b
    steps:
  mtaBuild:
    buildTarget: 'NEO'
  transportRequestCreate:
    developmentSystemId: 'SM1~ABAP/001'
  transportRequestUploadFile:
    applicationId: 'HCP'
