#Steps Specific Configuration
general:
  changeManagement:
    type:'SOLMAN'
    credentialsId:'CM'
    endpoint:'https://<backend-system>/sap/opu/odata/sap/AI_CRM_GW_CM_CI_SRV'
steps:
  mtaBuild:
    buildTarget: 'NEO'
  transportRequestCreate:
    developmentSystemId: 'SM1~ABAP/001'
  transportRequestUploadFile:
    applicationId: 'HCP'
