#Project Setup
general:
  collectTelemetryData: true
  changeManagement:
    type: 'NONE' # SOLMAN, CTS, NONE
    transportRequestLabel: 'TransportRequest\s?:'
    changeDocumentLabel: 'ChangeDocument\s?:'
    clientOpts: ''
    credentialsId: 'CM'
steps:
  mtaBuild:
    buildTarget: 'NEO'
  transportRequestCreate:
    developmentSystemId: 'SM1~ABAP/001'
  transportRequestUploadFile:
    applicationId: 'HCP'
